-- tools/tests/docs_reference — escribe docs/reference/*.md A PARTIR DEL JUEGO (catálogos reales): entidades, tiles,
-- decoraciones y modos, niveles y música. Son tablas, no prosa: nunca se editan a mano.
--   tools/tests/run.sh docs_reference            las reescribe
--   tools/tests/run.sh docs_reference CHECK=1    falla si alguna no está al día (va en la batería)
-- Vuelve a ejecutarlo al añadir o cambiar un tipo de entidad / tile / decoración, un nivel o una pista.
io.stdout:setvbuf('no')
love.filesystem.setSymlinksEnabled(true)
local CHECK = os.getenv('CHECK') == '1'
local ROOT = love.filesystem.getSource() .. '/../../../'
local stale = {}

local function write(name, lines)
    local text = table.concat(lines, '\n') .. '\n'
    local path = ROOT .. 'docs/reference/' .. name
    local f = io.open(path, 'rb')
    local old = f and f:read('*a'); if f then f:close() end
    if old == text then return end
    if CHECK then stale[#stale + 1] = name; return end
    f = assert(io.open(path, 'wb')); f:write(text); f:close()
    print('escrito docs/reference/' .. name)
end
local function walk(dir, out)
    for _, f in ipairs(love.filesystem.getDirectoryItems(dir .. '/.')) do
        local p = dir .. '/' .. f
        local info = love.filesystem.getInfo(p)
        if info and info.type == 'directory' then walk(p, out) elseif f:match('%.lua$') then out[#out + 1] = p end
    end
    return out
end
local function val(v)
    if type(v) == 'table' or type(v) == 'function' then return '…' end
    if v == nil then return '' end
    return tostring(v)
end
local function esc(s) return (tostring(s or ''):gsub('|', '\\|'):gsub('\n', ' ')) end
local HEAD = '<!-- GENERATED by tools/tests/run.sh docs_reference — do not edit by hand -->'

function love.load()
    require 'settings'
    FONT_SMALL = love.graphics.newFont(8); FONT_MED = FONT_SMALL; FONT_BIG = FONT_SMALL
    Input = require('src/network/Protocol').newInputStub()
    Sound = setmetatable({}, { __index = function() return function() end end })
    local json = require 'libs/json'
    local Entities = require 'src/world/entities/Entities'
    local ET = Entities.types
    local Tiles = require 'src/world/tiles/Tiles'
    local Decorations = require 'src/world/decorations/Decorations'
    local Modes = require 'src/world/modes/Modes'
    local Music = require 'src/audio/Music'
    local Worlds = require 'src/story/Worlds'

    -- ── entidades ──
    local srcOf = {}
    local typeFiles = walk('src/world/entities/types', {})
    table.sort(typeFiles)
    for _, f in ipairs(typeFiles) do
        local text = love.filesystem.read(f) or ''
        local base = f:match('([^/]+)%.lua$')
        for name in pairs(ET.byName) do
            if base == name then srcOf[name] = f
            elseif not srcOf[name] and text:find("'" .. name .. "'", 1, true) then srcOf[name] = f end
        end
    end
    for name in pairs(ET.byName) do            -- (el archivo con su mismo nombre manda aunque otro lo mencione antes)
        for _, f in ipairs(typeFiles) do if f:match('([^/]+)%.lua$') == name then srcOf[name] = f end end
    end
    local cats, byCat = {}, {}
    for name, d in pairs(ET.byName) do
        local c = d.category or 'Otros'
        if not byCat[c] then byCat[c] = {}; cats[#cats + 1] = c end
        table.insert(byCat[c], d)
    end
    table.sort(cats, function(a, b) local x, y = ET.categoryOrder(a), ET.categoryOrder(b); if x ~= y then return x < y end; return a < b end)
    local out = { HEAD, '# Entity types', '',
        'Every entity type registered in `src/world/entities/Entities.lua`, by editor category. **Id** is what level JSON',
        'and the network use; **Label** is the (Spanish) name in the editor. Own props = the type\'s extra properties',
        '(key: kind = default); every type also has the common props of `EntityTypes.COMMON` unless it hides them.', '' }
    for _, c in ipairs(cats) do
        out[#out + 1] = '## ' .. c; out[#out + 1] = ''
        out[#out + 1] = '| Id | Label | File | Flags | Own props |'; out[#out + 1] = '|---|---|---|---|---|'
        table.sort(byCat[c], function(a, b) return a.name < b.name end)
        for _, d in ipairs(byCat[c]) do
            local flags = {}
            if d.boss then flags[#flags + 1] = 'boss' end
            if d.pickup then flags[#flags + 1] = 'pickup' end
            if d.checkpoint then flags[#flags + 1] = 'checkpoint' end
            if d.activatable then flags[#flags + 1] = 'activatable' end
            if d.variant then flags[#flags + 1] = 'variant of `' .. tostring(d.variant.group) .. '`' end
            if d.placement == 'sub' then flags[#flags + 1] = 'sub-cell' end
            if d.ceilingOnly then flags[#flags + 1] = 'ceiling only' end
            for k in pairs(d.traits or {}) do flags[#flags + 1] = k end
            table.sort(flags)
            local props = {}
            for _, p in ipairs(d.props or {}) do props[#props + 1] = ('`%s`: %s = %s'):format(p.key, p.kind or '?', esc(val(p.default))) end
            out[#out + 1] = ('| `%s` | %s | `%s` | %s | %s |'):format(d.name, esc(d.label), (srcOf[d.name] or '?'):gsub('^src/world/entities/', ''), table.concat(flags, ', '), table.concat(props, ' · '))
        end
        out[#out + 1] = ''
    end
    write('entities.md', out)

    -- ── tiles ──
    out = { HEAD, '# Tile types', '',
        'Every tile registered in `src/world/tiles/Tiles.lua`. **Id** is stored in the level\'s `tiles` grid (see',
        '`src/world/tiles/TileCodec.lua` for the raw cell format: id + water + spikes). Global `TILE_<NAME>` = its id.', '',
        '| Id | Name | Label | Category | Collision | Material | Notes |', '|---|---|---|---|---|---|---|' }
    for _, t in ipairs(Tiles.types.list) do
        local n = {}
        if t.breakable then n[#n + 1] = 'breakable' end
        if t.toggle then n[#n + 1] = 'toggles to `' .. t.toggle .. '`' end
        if t.switchBlock then n[#n + 1] = 'ON/OFF block' end
        if t.thinIce then n[#n + 1] = 'thin ice' end
        if t.trigger then n[#n + 1] = 'trigger `' .. tostring(t.trigger) .. '`' end
        if t.editorHide then n[#n + 1] = 'hidden in editor' end
        if not t.fullHitbox then n[#n + 1] = 'partial hitbox' end
        if t.light then n[#n + 1] = 'gives light' end
        if t.joinGroup then n[#n + 1] = 'joins `' .. t.joinGroup .. '`' end
        out[#out + 1] = ('| %d | `%s` | %s | %s | %s%s | %s | %s |'):format(t.id, t.name, esc(t.label), esc(t.category), t.collision,
            t.dropThrough and ' (drop-through)' or '', t.material, table.concat(n, ', '))
    end
    out[#out + 1] = ''; out[#out + 1] = '## Materials'; out[#out + 1] = ''
    local mats = {}
    for name in pairs(Tiles.materials.byName) do mats[#mats + 1] = name end
    table.sort(mats)
    out[#out + 1] = '`src/world/tiles/materials/<name>.lua`: ' .. table.concat(mats, ', ') .. '.'
    write('tiles.md', out)

    -- ── decoraciones y modos ──
    out = { HEAD, '# Decoration types and game modes', '', '## Decorations', '',
        'Registered in `src/world/decorations/Decorations.lua` (level JSON key `foliage`). Render only.', '',
        '| Name | Label | Category | Placement | Light |', '|---|---|---|---|---|' }
    local decs = {}
    for _, d in ipairs(Decorations.types.list) do decs[#decs + 1] = d end
    table.sort(decs, function(a, b)
        local x, y = Decorations.types.categoryOrder(a.category), Decorations.types.categoryOrder(b.category)
        if x ~= y then return x < y end
        return a.name < b.name
    end)
    for _, d in ipairs(decs) do
        out[#out + 1] = ('| `%s` | %s | %s | %s | %s |'):format(d.name, esc(d.label), esc(d.category), d.placement, d.light and 'yes' or '')
    end
    out[#out + 1] = ''; out[#out + 1] = '## Online game modes'; out[#out + 1] = ''
    out[#out + 1] = 'Registered in `src/world/modes/Modes.lua`; texts are language keys `mode.<id>.*`.'; out[#out + 1] = ''
    out[#out + 1] = '| Id | File | Triggers it uses |'; out[#out + 1] = '|---|---|---|'
    for _, m in ipairs(Modes.list) do
        local tr = {}
        for k, v in pairs(m.triggers or {}) do tr[#tr + 1] = type(k) == 'number' and tostring(v) or tostring(k) end
        table.sort(tr)
        out[#out + 1] = ('| `%s` | `src/world/modes/%s.lua` | %s |'):format(m.id, m.id, table.concat(tr, ', '))
    end
    write('decorations-and-modes.md', out)

    -- ── niveles ──
    local where = {}
    for w, W in ipairs(Worlds.LIST) do
        for k, id in ipairs(W.levels) do where[id] = ('%d %s · %d'):format(w, W.id, k) end
        where[W.boss] = ('%d %s · boss'):format(w, W.id)
        if W.bonus then where[W.bonus] = ('%d %s · bonus'):format(w, W.id) end
    end
    local files = {}
    for _, f in ipairs(love.filesystem.getDirectoryItems('assets/levels')) do
        if f:match('%.json$') and not f:match('^_') and not f:match('^zz_tmp') and f ~= 'editor_playtest.json' then files[#files + 1] = f end
    end
    table.sort(files, function(a, b) return a:lower() < b:lower() end)
    out = { HEAD, '# Levels', '',
        'Every file in `assets/levels/` (' .. #files .. '). **Story** = world number, world id and position from',
        '`src/story/Worlds.lua` (empty = not in the story: online / Free Play only). **Modes** = the level\'s `"modes"` whitelist',
        '(empty = decided by each mode\'s `requires`). **Music** = catalog id.', '',
        '| File | Name (es / en) | Size | Story | Modes | Music | Bosses | Features |', '|---|---|---|---|---|---|---|---|' }
    for _, f in ipairs(files) do
        local ok, lv = pcall(json.decode, love.filesystem.read('assets/levels/' .. f))
        if ok and type(lv) == 'table' then
            local id = f:gsub('%.json$', '')
            local bosses, feats, n = {}, {}, {}
            for _, e in ipairs(lv.entities or {}) do
                local d = ET.byName[e.type]
                if d and d.boss then bosses[e.type] = true end
                n[e.type] = (n[e.type] or 0) + 1
            end
            local bl = {}
            for b in pairs(bosses) do bl[#bl + 1] = '`' .. b .. '`' end
            table.sort(bl)
            if lv.autoScroll then feats[#feats + 1] = 'auto-scroll' end
            if lv.dark then feats[#feats + 1] = 'dark' end
            if n.flood then feats[#feats + 1] = 'floods' end
            if n.pointarea then feats[#feats + 1] = n.pointarea .. ' point zone' .. (n.pointarea > 1 and 's' or '') end
            if lv.snow then feats[#feats + 1] = 'snowfall' end
            if lv.peaceful then feats[#feats + 1] = 'peaceful (test)' end
            if lv.parTime then feats[#feats + 1] = 'par ' .. lv.parTime .. ' s' end
            if lv.matchTime then feats[#feats + 1] = 'match ' .. lv.matchTime .. ' s' end
            if lv.depth then feats[#feats + 1] = 'depth ' .. lv.depth end
            out[#out + 1] = ('| `%s` | %s / %s | %dx%d | %s | %s | %s | %s | %s |'):format(id, esc(lv.name), esc(lv.name_en or '—'), lv.width or 0, lv.height or 0,
                where[id] or '', table.concat(lv.modes or {}, ', '), lv.music and ('`' .. lv.music .. '`') or '', table.concat(bl, ', '),
                (lv.background or 'meadow') .. (lv.time and (' ' .. lv.time) or '') .. (#feats > 0 and (' · ' .. table.concat(feats, ', ')) or ''))
        end
    end
    write('levels.md', out)

    -- ── música ──
    out = { HEAD, '# Music catalog', '',
        'From `assets/music/index.json` (' .. #Music.list .. ' tracks). Paths are relative to `assets/music/`. A track with **intro + loop**',
        'plays the intro once and then repeats the loop. `level` = offered as level music in the editor; `boss` = offered for boss zones.', '',
        '| Id | Name | Files | Volume | Use |', '|---|---|---|---|---|' }
    for _, t in ipairs(Music.list) do
        local files = t.file and ('`' .. t.file:gsub('^assets/music/', '') .. '`') or (('`%s` + `%s`'):format((t.intro or '—'):gsub('^assets/music/', ''), (t.loopFile or ''):gsub('^assets/music/', '')))
        local use = {}
        if t.level ~= false then use[#use + 1] = 'level' end
        if t.boss then use[#use + 1] = 'boss' end
        if not t.loops then use[#use + 1] = 'plays once' end
        out[#out + 1] = ('| `%s` | %s | %s | %s | %s |'):format(t.id, esc(t.name), files, val(t.volume), table.concat(use, ', '))
    end
    local al = {}
    for k, v in pairs(Music.aliases or {}) do al[#al + 1] = ('`%s` → `%s`'):format(k, v) end
    table.sort(al)
    out[#out + 1] = ''; out[#out + 1] = '## Aliases (old ids that still resolve)'; out[#out + 1] = ''
    out[#out + 1] = table.concat(al, ' · ')
    write('music.md', out)

    if CHECK then
        print(#stale == 0 and 'RESULTADO: OK (docs/reference al día)' or ('RESULTADO: FALLA — sin actualizar: ' .. table.concat(stale, ', ') .. ' (ejecuta tools/tests/run.sh docs_reference)'))
        love.event.quit(#stale == 0 and 0 or 1)
    else
        print('RESULTADO: OK'); love.event.quit(0)
    end
end
